Improvements to tos.py.
This latest version includes:
  * support for MIB600
  * a generic dump program (tos-dump) that has support for decoding the
    printf packets
  * a few example programs for some of the applications (Oscilloscope,
    MultihopOscilloscope, TestFtsp, TestLocalTime).


git-svn-id: http://tinyos-main.googlecode.com/svn/trunk@4449 285f258d-8064-b571-fbc6-9656dc998e90

diff --git a/apps/tests/deluge/Blink/burn b/apps/tests/deluge/Blink/burn
--- a/apps/tests/deluge/Blink/burn
+++ b/apps/tests/deluge/Blink/burn
@@ -1,41 +1,35 @@
 #!/bin/bash
 
-python -c '
-import sys
-try: 
-  import serial
-except ImportError, e: 
-  sys.exit(1)'
-
-if [[ $? != 0 ]]
-then
-  echo "Please install PySerial first." 
-  exit 2
-fi
-
 TOS_DELUGE=`type -p tos-deluge`
 if [[ ! -x ${TOS_DELUGE} ]] ; then 
     TOS_DELUGE=../../../../tools/tinyos/misc/tos-deluge
 fi 
 
+$TOS_DELUGE > /dev/null
+
+if [[ $? != 0 ]]
+then
+  echo "Unable to locate tos-deluge."
+  exit 2
+fi
+
 if [[ $# -ne 2 && $# -ne 3 ]]; then
-  echo "Usage: $0 <port> [<comm_port>] <platform>"
-  echo "  <port>       /dev/ttyUSB0"
-  echo "  <comm_port>  /dev/ttyUSB1"
-  echo "  <platform>   micaz, telosb, iris or epic"
+  echo "Usage: $0 <prog_source> <comm_source> <platform>"
+  echo "  <prog_source> bsl,PORT | mib510,PORT | eprb,PORT"
+  echo "  <comm_source> serial@PORT:SPEED | network@HOST:PORT"
+  echo "  <platform>    micaz | telosb | iris | epic"
   exit 2
 fi
 
 PPORT=$1
-CPORT=$1
-PLATFORM=$2
+CPORT=$2
+PLATFORM=$3
 
-if [ $# -eq 3 ]; then
- CPORT=$2
- PLATFORM=$3
-fi
-
-if [ ${PLATFORM} != 'micaz' -a ${PLATFORM} != 'telosb' -a ${PLATFORM} != 'iris' -a ${PLATFORM} != 'epic' ]; then
+if [ ${PLATFORM} != 'micaz' -a \
+     ${PLATFORM} != 'telosb' -a \
+     ${PLATFORM} != 'iris' -a \
+     ${PLATFORM} != 'epic' ]
+then
   echo "\"${PLATFORM}\" is not a supported platform"
   exit 2
 fi
@@ -49,16 +43,7 @@ fi
 make clean
 
 echo ============================ Compile and load Blink ============================
-if [ $PLATFORM == 'micaz' ]
-then
-  CFLAGS=-DDELUGE_BASESTATION make ${PLATFORM} install mib510,${PPORT}
-elif [ $PLATFORM == 'telosb' -o $PLATFORM == 'epic' ]
-then
-  CFLAGS=-DDELUGE_BASESTATION make ${PLATFORM} install bsl,${PPORT}
-elif [ $PLATFORM == 'iris' ]
-then
-  CFLAGS=-DDELUGE_BASESTATION make ${PLATFORM} install mib510,${PPORT}
-fi
+CFLAGS=-DDELUGE_BASESTATION make ${PLATFORM} install ${PPORT}
 
 
 echo '           +-------------------------------------------------------+'
@@ -74,7 +59,7 @@ echo  ============================= Compile a new Blink ========================
 CFLAGS=-DBLINK_REVERSE\ -DDELUGE_BASESTATION make ${PLATFORM}
 
 echo =============================== Upload the image ===============================
-${TOS_DELUGE} ${CPORT} ${PLATFORM} -i 1 build/${PLATFORM}/tos_image.xml
+${TOS_DELUGE} ${CPORT} -i 1 build/${PLATFORM}/tos_image.xml
 
 echo '       +----------------------------------------------------------------+'
 echo '       |                                                                |'
@@ -91,4 +76,4 @@ echo '       +----------------------------------------------------------------+'
 read
 
 echo =========================== Reboot the base station ============================
-${TOS_DELUGE} ${CPORT} ${PLATFORM} -r 1 
+${TOS_DELUGE} ${CPORT} -r 1 
diff --git a/apps/tests/deluge/Blink/burn-net b/apps/tests/deluge/Blink/burn-net
--- a/apps/tests/deluge/Blink/burn-net
+++ b/apps/tests/deluge/Blink/burn-net
@@ -5,6 +5,14 @@ if [[ ! -x ${TOS_DELUGE} ]] ; then
     TOS_DELUGE=../../../../tools/tinyos/misc/tos-deluge
 fi 
 
+$TOS_DELUGE > /dev/null
+
+if [[ $? != 0 ]]
+then
+  echo "Unable to locate tos-deluge."
+  exit 2
+fi
+
 if [ $# -ne 2 ]; then
   echo "Usage: $0 <platform> <number of motes>"
   echo "  <platform>         micaz, telosb or iris"
@@ -15,7 +23,11 @@ fi
 PLATFORM=$1
 NO_MOTES=$2
 
-if [ ${PLATFORM} != 'micaz' -a ${PLATFORM} != 'telosb' -a ${PLATFORM} != 'iris' ]; then
+if [ ${PLATFORM} != 'micaz' -a \
+     ${PLATFORM} != 'telosb' -a \
+     ${PLATFORM} != 'iris' \
+     ${PLATFORM} != 'epic' ]
+then
   echo "\"${PLAFTORM}\" is not a supported platform"
   exit 2
 fi
@@ -32,19 +44,10 @@ ID=0
 
 function burn_one() {
     ID=`expr $ID + 1`
-    echo -n ">>> Please plug mote $ID and type the programming port to continue: "
+    echo -n ">>> Please plug mote $ID and type the programming sorce (bsl,PORT | mib510,PORT | eprb,PORT): "
     read PORT
 
-    if [ ${PLATFORM} == 'micaz' ]
-    then
-	CFLAGS=$1 make ${PLATFORM} install,$ID mib510,${PORT}
-    elif [ ${PLATFORM} == 'telosb' ]
-    then
-	CFLAGS=$1 make ${PLATFORM} install,$ID bsl,${PORT}
-    elif [ ${PLATFORM} == 'iris' ]
-    then
-	CFLAGS=$1 make ${PLATFORM} install,$ID mib510,${PORT}
-    fi
+    CFLAGS=$1 make ${PLATFORM} install,$ID ${PORT}
 }
 
 while [[ ${NO_MOTES} > 1 ]]
@@ -54,9 +57,8 @@ do
 done
 echo ">>> Note: this last mote will be the basestation! <<<"
 burn_one -DDELUGE_BASESTATION
-echo -n ">>> Please plug mote $ID and type the communication port to continue: "
-read PORT
-BASESTATION_PORT=$PORT
+echo -n ">>> Please plug mote $ID and type the communication sorce (serial@PORT:SPEED | network@HOST:PORT) to continue: "
+read CPORT
 
 echo '   +------------------------------------------------------------------------+'
 echo '   |                                                                        |'
@@ -71,7 +73,7 @@ echo ============================= Compile a new Blink =========================
 CFLAGS=-DBLINK_REVERSE\ -DDELUGE_LIGHT_BASESTATION make ${PLATFORM} 
 
 echo ========= Upload the new image to the external flash of the last mote ==========
-${TOS_DELUGE} ${BASESTATION_PORT} ${PLATFORM} -i 1 build/${PLATFORM}/tos_image.xml
+${TOS_DELUGE} ${CPORT} -i 1 build/${PLATFORM}/tos_image.xml
 
 echo '            +-----------------------------------------------------+'
 echo '            |                                                     |'
@@ -85,7 +87,7 @@ echo '            +-----------------------------------------------------+'
 read
 
 echo ============================= Start dissemination ==============================
-${TOS_DELUGE} ${BASESTATION_PORT} ${PLATFORM} -dr 1
+${TOS_DELUGE} ${CPORT} -dr 1
 
 echo '         +------------------------------------------------------------+'
 echo '         |                                                            |'
