cross compiling in cygwin, added some other cygwin specific stuff

diff --git a/tools/tinyos/misc/tos-install-jni.in b/tools/tinyos/misc/tos-install-jni.in
--- a/tools/tinyos/misc/tos-install-jni.in
+++ b/tools/tinyos/misc/tos-install-jni.in
@@ -10,7 +10,22 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
-echo "Installing Java JNI code in $jni ... "
-for lib in $tinyoslibdir/*.@JNISUFFIX@; do
-  @INSTALLJNI@ $lib "$jni" || exit 1
-done
+if [ -x /bin/cygwin1.dll ]; then
+  java=`tos-locate-jre --java`
+  bits=32
+  if [ $? -ne 0 ]; then
+    echo "java command not found - assuming 32 bits"
+  elif file -L $java/java | grep -qe '64-bit|x86-64'; then #java7 on windows7 only prints x86-64
+    bits=64
+  fi
+  echo "Installing $bits-bit Java JNI code in $jni ... "
+  for lib in $tinyoslibdir/*-$bits.@JNISUFFIX@; do
+    realname=`basename $lib | sed -e s/-$bits\.@JNISUFFIX@/.@JNISUFFIX@/`
+    @INSTALLJNI@ $lib "$jni/$realname" || exit 1
+  done
+else
+  echo "Installing Java JNI code in $jni ... "
+  for lib in $tinyoslibdir/*.@JNISUFFIX@; do
+    @INSTALLJNI@ $lib "$jni" || exit 1
+  done
+fi
